spring:
  cloud:
    function:
      definition: executeTask;handleTaskResponse
    stream:
      bindings:
        task-request-out:
          destination: task-request
        executeTask-in-0:
          destination: task-request
          group: execute-app
          consumer:
            concurrency: 5
        executeTask-out-0:
          destination: task-response
        handleTaskResponse-in-0:
          destination: task-response
          group: client-app


  thymeleaf:
    prefix: classpath:/resources
  level:
    victor: DEBUG

