management.endpoints.web.exposure.include: "*"
management.endpoint.prometheus.enabled: true
management.endpoint.health.show-details: always
spring:
  cloud:
    function:
      definition: executeTask;handleTaskResponse;taskRequest
    stream:
      bindings:
        taskRequest-out-0:
          destination: task-request
        executeTask-in-0:
          destination: task-request
          group: execute-app
          consumer:
            concurrency: 5
        executeTask-out-0:
          destination: task-response
        handleTaskResponse-in-0:
          destination: task-response
          group: client-app


  thymeleaf:
    prefix: classpath:/resources
  level:
    victor: DEBUG

