management.endpoints.web.exposure.include: "*"

spring:
  cloud:
#    function:
#      definition: executeTask;handleTaskResponse;taskRequest
    stream:
      bindings:
        #config pt app "client"
        taskRequest-out-0:
          destination: task-request #numele in Rabbit
        handleTaskResponse-in-0:
          destination: task-response
          group: client-app

        #config pt app "provider"
        executeTask-in-0:
          destination: task-request
          consumer:
            concurrency: 5 #= mesaje in procesare simultan = pe cate threduri procesez mesaje din rabbit
          group: execute-app # util cand deployezi TaskExecutorApp pe mai multe instante, si toate trag din Rabbit mesaje.
        # pentru ca Rabbit sa considere mesajul livrat app tale, trebuie sa-i spui din fiecare instanta ca esti de fapt
        # acelasi "consumer group" = load balancing pe procesarea mesajului
        executeTask-out-0:
          destination: task-response



logging:
  level:
    victor: DEBUG

